### ISSUE TITLE
Newest release didn't create a build 

### ISSUE THREAD

**Issue by Fire-Swan** [binhex/arch-minecraftbedrockserver#8]
There was a release 2 hours ago but the builds on [github](https://github.com/binhex/arch-minecraftbedrockserver/pkgs/container/arch-minecraftbedrockserver) and [dockerhub ](https://hub.docker.com/r/binhex/arch-minecraftbedrockserver/tags) are 29 days old.

**Comment by binhex** [comment]
Fixed, please pull down.

**Comment by Fire-Swan** [comment]
Thank you!
